<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/GachaBot.Infrastructure/GachaBot.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../../test-sources/**/*" Link="test-sources/%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../src/GachaBot.Web/source-definitions.json" Link="source-definitions.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
